# render.yaml
services:
  - type: web
    name: vente-voitures
    env: python
    region: frankfurt  # ou virginia, oregon, singapore
    plan: free
    buildCommand: |
      bash build.sh
    startCommand: gunicorn config.wsgi:application
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vente-voitures-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: REQUIRE_POSTGRES
        value: true

databases:
  - name: vente-voitures-db
    plan: free
    region: frankfurt
    databaseName: vente_voitures
    user: vente_voitures_user
